# Generated by Django 3.2.13 on 2023-09-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carolsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformacao',
            name='over_the_years',
            field=models.CharField(choices=[('B', 'before 90'), ('W', 'while 90'), ('A', 'after 90')], max_length=1),
        ),
    ]
